<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413140255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(80) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE etablissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(80) NOT NULL, ville VARCHAR(80) NOT NULL, localisation VARCHAR(255) NOT NULL, type VARCHAR(80) DEFAULT NULL, image VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE filiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(80) NOT NULL, description TEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, categorie_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2ED05D9EBCF5E72D ON filiere (categorie_id)');
        $this->addSql('CREATE TABLE filiere_etablissement (filiere_id INT NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (filiere_id, etablissement_id))');
        $this->addSql('CREATE INDEX IDX_6707593E180AA129 ON filiere_etablissement (filiere_id)');
        $this->addSql('CREATE INDEX IDX_6707593EFF631228 ON filiere_etablissement (etablissement_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE filiere ADD CONSTRAINT FK_2ED05D9EBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593E180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE filiere DROP CONSTRAINT FK_2ED05D9EBCF5E72D');
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593E180AA129');
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593EFF631228');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE etablissement');
        $this->addSql('DROP TABLE filiere');
        $this->addSql('DROP TABLE filiere_etablissement');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
