<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507185116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT DEFAULT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expediteur_id INT DEFAULT NULL, forum_categorie_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F10335F61 ON message (expediteur_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F842B116A ON message (forum_categorie_id)');
        $this->addSql('CREATE TABLE user_categorie (user_id INT NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (user_id, categorie_id))');
        $this->addSql('CREATE INDEX IDX_499D5BD0A76ED395 ON user_categorie (user_id)');
        $this->addSql('CREATE INDEX IDX_499D5BD0BCF5E72D ON user_categorie (categorie_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F842B116A FOREIGN KEY (forum_categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE user_categorie ADD CONSTRAINT FK_499D5BD0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_categorie ADD CONSTRAINT FK_499D5BD0BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F10335F61');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F842B116A');
        $this->addSql('ALTER TABLE user_categorie DROP CONSTRAINT FK_499D5BD0A76ED395');
        $this->addSql('ALTER TABLE user_categorie DROP CONSTRAINT FK_499D5BD0BCF5E72D');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE user_categorie');
    }
}
